"use client"

import { useState } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

function AnimatedHeader({ type }: { type: string }) {
  const base = "relative h-24 mb-4 bg-gradient-to-r from-gray-800/70 to-gray-700/50 rounded-lg overflow-hidden border border-slate-700/40"
  if (type === "print") return <div className={base}><div className="absolute left-1/2 -translate-x-1/2 top-3 w-10 h-7 bg-cyan-400/25 border border-cyan-300/70 rounded"><div className="absolute left-1/2 -translate-x-1/2 -bottom-3 w-1 h-3 bg-cyan-300"/></div><div className="absolute bottom-4 left-[14%] h-1.5 bg-cyan-400 rounded project-layer"/><div className="absolute bottom-8 left-[22%] h-1 w-[56%] bg-blue-400/70 rounded"/><div className="absolute inset-y-0 w-px bg-cyan-300 project-scan"/></div>
  if (type === "fish") return <div className={base}><div className="absolute left-1/2 top-1/2 -translate-y-1/2 text-4xl project-drift">🐟</div><div className="absolute inset-y-2 w-px bg-blue-300 shadow-[0_0_12px_#60a5fa] project-scan"/><div className="absolute left-5 top-4 w-2 h-2 rounded-full border border-cyan-300 animate-pulse"/><div className="absolute right-8 bottom-5 w-3 h-3 rounded-full border border-blue-300 animate-pulse"/></div>
  if (type === "pingpong") return <div className={base}><div className="absolute left-5 top-1/2 -translate-y-1/2 w-1 h-9 bg-cyan-400 rounded"/><div className="absolute right-5 top-1/2 -translate-y-1/2 w-1 h-9 bg-blue-400 rounded"/><div className="absolute left-1/2 top-1/2 w-3 h-3 bg-cyan-300 rounded-full shadow-[0_0_14px_#67e8f9] project-ball"/><div className="absolute left-4 right-4 top-1/2 h-px bg-cyan-400/40"/></div>
  if (type === "gan") return <div className={base}><div className="absolute left-8 top-6 grid grid-cols-2 gap-2">{[0,1,2,3].map(i=><span key={i} className="w-2 h-2 rounded-full bg-purple-400 animate-pulse"/>)}</div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-9 h-9 border-2 border-fuchsia-400 bg-purple-500/20 project-generate"/><div className="absolute right-8 top-5 w-12 h-12 grid grid-cols-2 gap-1">{[0,1,2,3].map(i=><span key={i} className="rounded bg-gradient-to-br from-purple-400/70 to-pink-400/70 animate-pulse"/>)}</div></div>
  if (type === "face") return <div className={base}><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-4xl">🙂</div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-16 h-16 border border-emerald-400 rounded-lg animate-pulse"/><div className="absolute inset-y-3 w-px bg-emerald-300 project-scan"/></div>
  if (type === "health") return <div className={base}><div className="absolute left-7 top-1/2 -translate-y-1/2 text-4xl project-heart">❤️</div><svg className="absolute left-24 right-5 top-6 h-12 w-[65%]" viewBox="0 0 240 50"><polyline points="0,28 35,28 50,10 67,43 83,22 98,28 140,28 155,14 170,38 187,28 240,28" fill="none" stroke="#fb7185" strokeWidth="3"/><line x1="0" y1="0" x2="0" y2="50" stroke="#fda4af" className="project-scan"/></svg></div>
  if (type === "robot") return <div className={base}><div className="absolute left-10 top-1/2 -translate-y-1/2 text-4xl project-drift">🤖</div><div className="absolute right-8 top-5 w-4 h-14 rounded bg-orange-400/70"/><div className="absolute left-[55%] top-1/2 -translate-y-1/2 w-8 h-8 rounded-full border-2 border-amber-300 project-wave"/><div className="absolute left-[55%] top-1/2 -translate-y-1/2 w-8 h-8 rounded-full border-2 border-orange-300 project-wave [animation-delay:.6s]"/></div>
  if (type === "mask") return <div className={base}><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-4xl">😷</div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-16 h-16 border-2 border-green-400 rounded-md animate-pulse"/><span className="absolute right-5 top-4 text-xs text-green-300 border border-green-400/60 rounded px-2 py-1">MASK ✓</span><div className="absolute inset-y-3 w-px bg-green-300 project-scan"/></div>
  return <div className={base}><div className="absolute left-7 top-6 text-4xl project-book">📚</div><div className="absolute right-7 top-5 text-4xl">👤</div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 text-xl text-violet-300 animate-pulse">⇄</div><div className="absolute bottom-3 left-5 right-5 h-px bg-violet-400/40"/></div>
}

export default function Projects() {
  const [hoveredProject, setHoveredProject] = useState<number | null>(null)
  const projects = [
    {title:"AI-Assisted 3D Concrete Printing",description:"Applied AI and computer-vision methods during my internship at Mechatronics Innovation Lab. Worked with camera recordings, image extraction and annotation, model development for identifying cement/concrete, testing, and geometric width analysis of printed structures.",technologies:["AI","Computer Vision","Image Analysis","Data Annotation"],icon:"🏗️",gradient:"from-cyan-500 to-blue-500",features:["Real-world technical system","Model development & testing","Geometric analysis"],animationType:"print"},
    {title:"Underwater Fish Deformity Analysis",description:"Computer-vision project using underwater-camera imagery and geometric image analysis to investigate visible deformities in fish and extract relevant structural characteristics.",technologies:["Computer Vision","Image Processing","Geometric Analysis"],icon:"🐟",gradient:"from-blue-500 to-indigo-500",features:["Underwater imagery","Visual analysis","Geometric measurements"],animationType:"fish"},
    {title:"Reinforcement Learning Ping-Pong AI",description:"Built a reinforcement-learning project in which an agent learns control behaviour through repeated interaction, actions and reward feedback in a ping-pong environment.",technologies:["Reinforcement Learning","Python"],icon:"🏓",gradient:"from-cyan-500 to-blue-500",features:["Reward-based learning","Agent interaction","Iterative learning"],animationType:"pingpong"},
    {title:"Generative Adversarial Networks (GANs)",description:"Explored generative adversarial networks as part of my AI studies, working with the adversarial training concept of a generator and discriminator learning against each other to produce generated outputs.",technologies:["Deep Learning","GANs","Neural Networks"],icon:"🧠",gradient:"from-purple-500 to-pink-500",features:["Generative modelling","Adversarial training","Deep learning"],animationType:"gan"},
    {title:"Face Recognition Attendance Prototype",description:"Developed a computer-vision prototype exploring face recognition for classroom attendance, while also considering privacy limitations and responsible use of biometric identification.",technologies:["Computer Vision","Face Recognition","Python"],icon:"👁️",gradient:"from-emerald-500 to-teal-500",features:["Face recognition","Attendance concept","Privacy considerations"],animationType:"face"},
    {title:"Health Tracking Application — Current Project",description:"Developing a health-tracking application focused on useful data tracking, clear user experience and responsible boundaries around sensitive health information and AI-assisted features.",technologies:["Application Development","Data Tracking","UI/UX","Responsible AI"],icon:"❤️",gradient:"from-pink-500 to-rose-500",features:["Health data tracking","User-focused design","Privacy-aware development"],animationType:"health"},
    {title:"Autonomous Robot & Sensor Integration — Current Project",description:"Building a small mobile robotics platform while developing hands-on experience with Arduino, Python and ROS2. Currently integrating ultrasonic distance sensing, serial communication and software-based obstacle decisions, with planned progression toward ROS2 sensor publishing, robot control, mapping and autonomous navigation.",technologies:["Arduino","Python","ROS2 (learning)","Sensors","Serial Communication"],icon:"🤖",gradient:"from-orange-500 to-amber-500",features:["Ultrasonic sensing","Hardware–software integration","ROS2 progression planned"],animationType:"robot"},
    {title:"Face Mask Detection",description:"Developed a computer-vision project for detecting whether a face is wearing a mask, applying image-based classification and visual detection concepts.",technologies:["Computer Vision","Machine Learning","Python"],icon:"😷",gradient:"from-green-500 to-emerald-500",features:["Visual detection","Image classification","Applied computer vision"],animationType:"mask"},
    {title:"Book Marketplace & Lending Platform",description:"Built a software platform for books where users can browse, borrow, buy and sell titles, combining application development with user and inventory workflows.",technologies:["Software Development","Web Development","Database","Application Design"],icon:"📚",gradient:"from-indigo-500 to-purple-500",features:["Borrow, buy & sell workflows","Book catalogue","User-focused application"],animationType:"books"},
  ]
  return <section id="projects" className="py-20 relative"><div className="container mx-auto px-4"><div className="text-center mb-12"><h2 className="text-4xl font-bold mb-4 glow-text">Selected Technical Projects</h2><p className="text-xl text-gray-300 max-w-3xl mx-auto">Selected work across artificial intelligence, computer vision, software development and current technical interests.</p></div><div className="max-w-7xl mx-auto"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{projects.map((project,index)=><Card key={index} className={`glow-border bg-gray-900/50 backdrop-blur-sm card-3d transition-all duration-500 hover:scale-105 ${hoveredProject===index?"glow-border-purple":""}`} onMouseEnter={()=>setHoveredProject(index)} onMouseLeave={()=>setHoveredProject(null)}><CardContent className="p-6 h-full flex flex-col"><AnimatedHeader type={project.animationType}/><div className="flex items-start gap-3 mb-3"><div className={`w-12 h-12 shrink-0 rounded-lg bg-gradient-to-r ${project.gradient} flex items-center justify-center text-2xl shadow-lg`}>{project.icon}</div><h3 className={`text-xl font-semibold bg-gradient-to-r ${project.gradient} bg-clip-text text-transparent`}>{project.title}</h3></div><p className="text-gray-300 mb-5 leading-relaxed">{project.description}</p><div className="mb-5"><h4 className="text-sm font-medium text-gray-400 mb-2">Highlights</h4><ul className="space-y-1 text-sm text-gray-400">{project.features.map((f,i)=><li key={i}>⚡ {f}</li>)}</ul></div><div className="flex flex-wrap gap-2 mt-auto">{project.technologies.map((t,i)=><Badge key={i} variant="outline" className="text-xs glow-border">{t}</Badge>)}</div></CardContent></Card>)}</div></div></div></section>
}
